<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <OutputType>Exe</OutputType>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FluentAssertions" Version="8.11.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="10.0.12" />
    <PackageReference Include="Microsoft.Extensions.TimeProvider.Testing" Version="10.10.0" />
    <PackageReference Include="NSubstitute" Version="6.2.0" />
    <PackageReference Include="xunit.v3" Version="4.0.1" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Ledger.Dashboards\Ledger.Dashboards.csproj" />
    <ProjectReference Include="..\Ledger.Domain\Ledger.Domain.csproj" />
    <ProjectReference Include="..\Ledger.Repository\Ledger.Repository.csproj" />
    <ProjectReference Include="..\Ledger.Service\Ledger.Service.csproj" />
  </ItemGroup>

</Project>
